### ISSUE TITLE
PM Issue

### ISSUE THREAD

**Issue by noahspooner** [noahspooner/TimeZoneConverter#1]
1PM, 2PM, 3PM, ect... display as 13PM, 14PM, 15PM, ect...

**Comment by sonuraghuwanshi** [comment]
I would like to resolve this issue. Can you please allow me to work on this?

**Comment by noahspooner** [comment]
Ok

**Comment by noahspooner** [comment]
I have given you access

**Comment by sonuraghuwanshi** [comment]
I have made a pull request. Please check that.

**Comment by noahspooner** [comment]
I have and I like it, good work!

**Comment by sonuraghuwanshi** [comment]
I think you have closed the pull request. Instead of this, you should merge pull request
